@startuml
'https://plantuml.com/class-diagram
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods
hide interface attributes

package MasterMind{

    package Controller{
        class MasterController{

        }
    }
    package Model {
        class MasterMindGame{

        }
        interface Observer{
        }
        class Round{
        }
        class Game{
        }


    }
    package View {
        class GameWindow {

        }
        class StartWindow{
        }
        class EndGameWindow{
        }
    }
}
GameWindow ...|> Observer
StartWindow ...|> Observer
EndGameWindow ...|> Observer

Game *---> Round : est un ensemble de

MasterMindGame o--> Observer : < observe

@enduml