@startuml
'https://plantuml.com/class-diagram
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods
hide interface attributes

package MasterMind{

    package Controller{
        class MasterController{

        }
    }
    package Model {
        class MasterMind{

        }
        interface Observer{
        }
    }
    package View {
        class MainWindow Implements Observer{

        }
    }
}


@enduml